apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    app: login
spec:
  type: NodePort
  selector:
    app: login
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: notes
  labels:
    app: notes
spec:
  type: NodePort
  selector:
    app: notes
  ports:
  - port: 5051
    targetPort: 5051
    nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  type: ClusterIP
  selector:
    app: db-service
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 1
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: localhost:5000/login
        ports:
        - containerPort: 5050

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  selector:
    matchLabels:
      app: notes
  replicas: 1
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: localhost:5000/notes
        ports:
        - containerPort: 5051
        env:
        - name: DB_HOST
          value: db-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db
          image: localhost:5000/db
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
        - name: faker
          image: localhost:5000/faker
          volumeMounts:
            - name: db-data
              mountPath: /data
      volumes:
        - name: db-data
          emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: http
              containerPort: 8080
            - name: jnlp
              containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer