apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  selector:
    app: db-service
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    app: login
spec:
  selector:
    app: login
  ports:
    - name: http
      port: 5050
      targetPort: 5050
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notes
  labels:
    app: notes
spec:
  selector:
    app: notes
  ports:
    - name: http
      port: 5051
      targetPort: 5051
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service
        image: localhost:5000/bd
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: localhost:5000/login
        ports:
        - containerPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: localhost:5000/notes
        ports:
        - containerPort: 5051
        env:
        - name: LOGIN_SERVICE_HOST
          value: login
        - name: LOGIN_SERVICE_PORT
          value: "5050"
---
apiVersion: v1
kind: Service
metadata:
  name: notes-external
  labels:
    app: notes
spec:
  selector:
    app: notes
  ports:
    - name: http
      port: 5051
      targetPort: 5051
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: login-external
  labels:
    app: login
spec:
  selector:
    app: login
  ports:
    - name: http
      port: 5050
      targetPort: 5050
  type: LoadBalancer