version: '3.3'  # version of compose format

services:
  db-service:
      image: localhost:5000/bd
      hostname: db-service
      ports:
        - 3306:3306  # host:container
      depends_on:
        - login   
        - notes
                    
      networks:
        sample:
          aliases:
            - db-service
  login:
    image: localhost:5000/login
    hostname: login
    ports:
      - 5050:5050  
    networks:
      sample:
        aliases:
          - login

  notes:
    image: localhost:5000/notes
    hostname: notes
    ports:
      - 5051:5051  # host:container
    depends_on:
      - login                            
    networks:
      sample:
        aliases:
          - login
  
networks:
  sample: