CREATE DATABASE IF NOT EXISTS gestn;

GRANT ALL PRIVILEGES ON gestn.* TO 'lepoxa'@'%';

USE gestn;

create table accountsProf(
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,

    typeAcc VARCHAR(50) NOT NULL,
    matiere VARCHAR(50) NOT NULL,
    PRIMARY KEY ( username )
    );
create table accountsEtd(
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,

    typeAcc VARCHAR(50) NOT NULL,
    PRIMARY KEY ( username )
    );

    
create table notes(
     username VARCHAR(50) NOT NULL,
     matiere VARCHAR(50) NOT NULL,
     note integer(10) NOT NULL
     );

INSERT INTO `notes` (username ,matiere, note) VALUES ("achang@example.org", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("achang@example.org", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("achang@example.org", "Statistiques", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("achang@example.org", "Communication", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("achang@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("achang@example.org", "Analyse Numérique", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("ashleypham@example.org", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("ashleypham@example.org", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("ashleypham@example.org", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("ashleypham@example.org", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("ashleypham@example.org", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("ashleypham@example.org", "Analyse Numérique", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davismichael@example.org", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davismichael@example.org", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davismichael@example.org", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davismichael@example.org", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davismichael@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davismichael@example.org", "Analyse Numérique", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brittanyanderson@example.net", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brittanyanderson@example.net", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brittanyanderson@example.net", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brittanyanderson@example.net", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brittanyanderson@example.net", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brittanyanderson@example.net", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kevingriffith@example.com", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kevingriffith@example.com", "Reseau", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kevingriffith@example.com", "Statistiques", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kevingriffith@example.com", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kevingriffith@example.com", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kevingriffith@example.com", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("judy80@example.com", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("judy80@example.com", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("judy80@example.com", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("judy80@example.com", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("judy80@example.com", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("judy80@example.com", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("washingtonjose@example.org", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("washingtonjose@example.org", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("washingtonjose@example.org", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("washingtonjose@example.org", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("washingtonjose@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("washingtonjose@example.org", "Analyse Numérique", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stacie60@example.org", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stacie60@example.org", "Reseau", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stacie60@example.org", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stacie60@example.org", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stacie60@example.org", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stacie60@example.org", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellbennett@example.org", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellbennett@example.org", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellbennett@example.org", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellbennett@example.org", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellbennett@example.org", "Machine Learning", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellbennett@example.org", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("raustin@example.org", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("raustin@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("raustin@example.org", "Statistiques", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("raustin@example.org", "Communication", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("raustin@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("raustin@example.org", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("pattersonbelinda@example.org", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("pattersonbelinda@example.org", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("pattersonbelinda@example.org", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("pattersonbelinda@example.org", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("pattersonbelinda@example.org", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("pattersonbelinda@example.org", "Analyse Numérique", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xglenn@example.com", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xglenn@example.com", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xglenn@example.com", "Statistiques", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xglenn@example.com", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xglenn@example.com", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xglenn@example.com", "Analyse Numérique", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hadams@example.net", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hadams@example.net", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hadams@example.net", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hadams@example.net", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hadams@example.net", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hadams@example.net", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kelly23@example.net", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kelly23@example.net", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kelly23@example.net", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kelly23@example.net", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kelly23@example.net", "Machine Learning", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kelly23@example.net", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gilbertkarina@example.net", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gilbertkarina@example.net", "Reseau", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gilbertkarina@example.net", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gilbertkarina@example.net", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gilbertkarina@example.net", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gilbertkarina@example.net", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("alexanderfitzgerald@example.org", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("alexanderfitzgerald@example.org", "Reseau", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("alexanderfitzgerald@example.org", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("alexanderfitzgerald@example.org", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("alexanderfitzgerald@example.org", "Machine Learning", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("alexanderfitzgerald@example.org", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("taylor46@example.org", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("taylor46@example.org", "Reseau", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("taylor46@example.org", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("taylor46@example.org", "Communication", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("taylor46@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("taylor46@example.org", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xroman@example.com", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xroman@example.com", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xroman@example.com", "Statistiques", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xroman@example.com", "Communication", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xroman@example.com", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xroman@example.com", "Analyse Numérique", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidcole@example.org", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidcole@example.org", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidcole@example.org", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidcole@example.org", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidcole@example.org", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidcole@example.org", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gloverabigail@example.net", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gloverabigail@example.net", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gloverabigail@example.net", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gloverabigail@example.net", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gloverabigail@example.net", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("gloverabigail@example.net", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanreid@example.org", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanreid@example.org", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanreid@example.org", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanreid@example.org", "Communication", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanreid@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanreid@example.org", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robertbarnes@example.com", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robertbarnes@example.com", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robertbarnes@example.com", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robertbarnes@example.com", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robertbarnes@example.com", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robertbarnes@example.com", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnaustin@example.com", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnaustin@example.com", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnaustin@example.com", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnaustin@example.com", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnaustin@example.com", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnaustin@example.com", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("patricia10@example.net", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("patricia10@example.net", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("patricia10@example.net", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("patricia10@example.net", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("patricia10@example.net", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("patricia10@example.net", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("lfranco@example.org", "Cloud Computing", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("lfranco@example.org", "Reseau", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("lfranco@example.org", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("lfranco@example.org", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("lfranco@example.org", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("lfranco@example.org", "Analyse Numérique", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("amack@example.org", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("amack@example.org", "Reseau", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("amack@example.org", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("amack@example.org", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("amack@example.org", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("amack@example.org", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("donnareynolds@example.net", "Cloud Computing", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("donnareynolds@example.net", "Reseau", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("donnareynolds@example.net", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("donnareynolds@example.net", "Communication", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("donnareynolds@example.net", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("donnareynolds@example.net", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smiles@example.org", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smiles@example.org", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smiles@example.org", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smiles@example.org", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smiles@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smiles@example.org", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("newtonamy@example.net", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("newtonamy@example.net", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("newtonamy@example.net", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("newtonamy@example.net", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("newtonamy@example.net", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("newtonamy@example.net", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("reedmegan@example.com", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("reedmegan@example.com", "Reseau", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("reedmegan@example.com", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("reedmegan@example.com", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("reedmegan@example.com", "Machine Learning", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("reedmegan@example.com", "Analyse Numérique", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cheryl93@example.com", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cheryl93@example.com", "Reseau", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cheryl93@example.com", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cheryl93@example.com", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cheryl93@example.com", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cheryl93@example.com", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("harrisonkathryn@example.org", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("harrisonkathryn@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("harrisonkathryn@example.org", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("harrisonkathryn@example.org", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("harrisonkathryn@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("harrisonkathryn@example.org", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("houseduane@example.net", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("houseduane@example.net", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("houseduane@example.net", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("houseduane@example.net", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("houseduane@example.net", "Machine Learning", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("houseduane@example.net", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("crystalmontoya@example.com", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("crystalmontoya@example.com", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("crystalmontoya@example.com", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("crystalmontoya@example.com", "Communication", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("crystalmontoya@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("crystalmontoya@example.com", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brenda30@example.com", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brenda30@example.com", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brenda30@example.com", "Statistiques", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brenda30@example.com", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brenda30@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brenda30@example.com", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("karen52@example.com", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("karen52@example.com", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("karen52@example.com", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("karen52@example.com", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("karen52@example.com", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("karen52@example.com", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian04@example.org", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian04@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian04@example.org", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian04@example.org", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian04@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian04@example.org", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mcconnellelizabeth@example.net", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mcconnellelizabeth@example.net", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mcconnellelizabeth@example.net", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mcconnellelizabeth@example.net", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mcconnellelizabeth@example.net", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mcconnellelizabeth@example.net", "Analyse Numérique", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("upatterson@example.org", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("upatterson@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("upatterson@example.org", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("upatterson@example.org", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("upatterson@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("upatterson@example.org", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanjohnson@example.org", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanjohnson@example.org", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanjohnson@example.org", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanjohnson@example.org", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanjohnson@example.org", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jordanjohnson@example.org", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hriley@example.org", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hriley@example.org", "Reseau", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hriley@example.org", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hriley@example.org", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hriley@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hriley@example.org", "Analyse Numérique", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kcook@example.com", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kcook@example.com", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kcook@example.com", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kcook@example.com", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kcook@example.com", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kcook@example.com", "Analyse Numérique", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnsonjoshua@example.org", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnsonjoshua@example.org", "Reseau", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnsonjoshua@example.org", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnsonjoshua@example.org", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnsonjoshua@example.org", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("johnsonjoshua@example.org", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellkathryn@example.com", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellkathryn@example.com", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellkathryn@example.com", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellkathryn@example.com", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellkathryn@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mitchellkathryn@example.com", "Analyse Numérique", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smeyer@example.org", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smeyer@example.org", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smeyer@example.org", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smeyer@example.org", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smeyer@example.org", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("smeyer@example.org", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robert41@example.com", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robert41@example.com", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robert41@example.com", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robert41@example.com", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robert41@example.com", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robert41@example.com", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("rossbrianna@example.org", "Cloud Computing", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("rossbrianna@example.org", "Reseau", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("rossbrianna@example.org", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("rossbrianna@example.org", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("rossbrianna@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("rossbrianna@example.org", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bryan87@example.net", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bryan87@example.net", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bryan87@example.net", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bryan87@example.net", "Communication", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bryan87@example.net", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bryan87@example.net", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david84@example.net", "Cloud Computing", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david84@example.net", "Reseau", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david84@example.net", "Statistiques", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david84@example.net", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david84@example.net", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david84@example.net", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("coopersarah@example.com", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("coopersarah@example.com", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("coopersarah@example.com", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("coopersarah@example.com", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("coopersarah@example.com", "Machine Learning", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("coopersarah@example.com", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xfoley@example.net", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xfoley@example.net", "Reseau", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xfoley@example.net", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xfoley@example.net", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xfoley@example.net", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("xfoley@example.net", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("marytran@example.org", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("marytran@example.org", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("marytran@example.org", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("marytran@example.org", "Communication", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("marytran@example.org", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("marytran@example.org", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian87@example.com", "Cloud Computing", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian87@example.com", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian87@example.com", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian87@example.com", "Communication", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian87@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("brian87@example.com", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stephendawson@example.net", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stephendawson@example.net", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stephendawson@example.net", "Statistiques", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stephendawson@example.net", "Communication", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stephendawson@example.net", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("stephendawson@example.net", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("scottevans@example.com", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("scottevans@example.com", "Reseau", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("scottevans@example.com", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("scottevans@example.com", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("scottevans@example.com", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("scottevans@example.com", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("travisjames@example.net", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("travisjames@example.net", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("travisjames@example.net", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("travisjames@example.net", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("travisjames@example.net", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("travisjames@example.net", "Analyse Numérique", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wellsalexandra@example.net", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wellsalexandra@example.net", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wellsalexandra@example.net", "Statistiques", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wellsalexandra@example.net", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wellsalexandra@example.net", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wellsalexandra@example.net", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("richardsoncatherine@example.org", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("richardsoncatherine@example.org", "Reseau", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("richardsoncatherine@example.org", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("richardsoncatherine@example.org", "Communication", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("richardsoncatherine@example.org", "Machine Learning", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("richardsoncatherine@example.org", "Analyse Numérique", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jamiemay@example.org", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jamiemay@example.org", "Reseau", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jamiemay@example.org", "Statistiques", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jamiemay@example.org", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jamiemay@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jamiemay@example.org", "Analyse Numérique", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("christophersantos@example.com", "Cloud Computing", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("christophersantos@example.com", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("christophersantos@example.com", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("christophersantos@example.com", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("christophersantos@example.com", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("christophersantos@example.com", "Analyse Numérique", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("justin24@example.org", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("justin24@example.org", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("justin24@example.org", "Statistiques", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("justin24@example.org", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("justin24@example.org", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("justin24@example.org", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nwhite@example.com", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nwhite@example.com", "Reseau", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nwhite@example.com", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nwhite@example.com", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nwhite@example.com", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nwhite@example.com", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cameronbriggs@example.com", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cameronbriggs@example.com", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cameronbriggs@example.com", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cameronbriggs@example.com", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cameronbriggs@example.com", "Machine Learning", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("cameronbriggs@example.com", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("qwallace@example.com", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("qwallace@example.com", "Reseau", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("qwallace@example.com", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("qwallace@example.com", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("qwallace@example.com", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("qwallace@example.com", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nmartinez@example.com", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nmartinez@example.com", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nmartinez@example.com", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nmartinez@example.com", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nmartinez@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("nmartinez@example.com", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("groberts@example.org", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("groberts@example.org", "Reseau", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("groberts@example.org", "Statistiques", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("groberts@example.org", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("groberts@example.org", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("groberts@example.org", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("collinssandra@example.com", "Cloud Computing", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("collinssandra@example.com", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("collinssandra@example.com", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("collinssandra@example.com", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("collinssandra@example.com", "Machine Learning", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("collinssandra@example.com", "Analyse Numérique", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wilsonricky@example.com", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wilsonricky@example.com", "Reseau", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wilsonricky@example.com", "Statistiques", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wilsonricky@example.com", "Communication", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wilsonricky@example.com", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("wilsonricky@example.com", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("veverett@example.net", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("veverett@example.net", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("veverett@example.net", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("veverett@example.net", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("veverett@example.net", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("veverett@example.net", "Analyse Numérique", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davisgarrett@example.net", "Cloud Computing", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davisgarrett@example.net", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davisgarrett@example.net", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davisgarrett@example.net", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davisgarrett@example.net", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davisgarrett@example.net", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("carterstephen@example.org", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("carterstephen@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("carterstephen@example.org", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("carterstephen@example.org", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("carterstephen@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("carterstephen@example.org", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("william04@example.org", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("william04@example.org", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("william04@example.org", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("william04@example.org", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("william04@example.org", "Machine Learning", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("william04@example.org", "Analyse Numérique", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("caseyjoanna@example.org", "Cloud Computing", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("caseyjoanna@example.org", "Reseau", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("caseyjoanna@example.org", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("caseyjoanna@example.org", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("caseyjoanna@example.org", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("caseyjoanna@example.org", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david79@example.org", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david79@example.org", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david79@example.org", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david79@example.org", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david79@example.org", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("david79@example.org", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("floreslauren@example.org", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("floreslauren@example.org", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("floreslauren@example.org", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("floreslauren@example.org", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("floreslauren@example.org", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("floreslauren@example.org", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("drichards@example.org", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("drichards@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("drichards@example.org", "Statistiques", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("drichards@example.org", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("drichards@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("drichards@example.org", "Analyse Numérique", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("steven63@example.com", "Cloud Computing", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("steven63@example.com", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("steven63@example.com", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("steven63@example.com", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("steven63@example.com", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("steven63@example.com", "Analyse Numérique", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mark33@example.org", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mark33@example.org", "Reseau", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mark33@example.org", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mark33@example.org", "Communication", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mark33@example.org", "Machine Learning", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mark33@example.org", "Analyse Numérique", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("codyglass@example.net", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("codyglass@example.net", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("codyglass@example.net", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("codyglass@example.net", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("codyglass@example.net", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("codyglass@example.net", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("samuelcarlson@example.org", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("samuelcarlson@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("samuelcarlson@example.org", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("samuelcarlson@example.org", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("samuelcarlson@example.org", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("samuelcarlson@example.org", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("phillip65@example.com", "Cloud Computing", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("phillip65@example.com", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("phillip65@example.com", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("phillip65@example.com", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("phillip65@example.com", "Machine Learning", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("phillip65@example.com", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("imorgan@example.com", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("imorgan@example.com", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("imorgan@example.com", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("imorgan@example.com", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("imorgan@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("imorgan@example.com", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kaylalucero@example.com", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kaylalucero@example.com", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kaylalucero@example.com", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kaylalucero@example.com", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kaylalucero@example.com", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("kaylalucero@example.com", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("danthony@example.org", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("danthony@example.org", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("danthony@example.org", "Statistiques", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("danthony@example.org", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("danthony@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("danthony@example.org", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robin07@example.org", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robin07@example.org", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robin07@example.org", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robin07@example.org", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robin07@example.org", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("robin07@example.org", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jacquelinewilkins@example.com", "Cloud Computing", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jacquelinewilkins@example.com", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jacquelinewilkins@example.com", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jacquelinewilkins@example.com", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jacquelinewilkins@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jacquelinewilkins@example.com", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hawkinsvictoria@example.net", "Cloud Computing", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hawkinsvictoria@example.net", "Reseau", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hawkinsvictoria@example.net", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hawkinsvictoria@example.net", "Communication", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hawkinsvictoria@example.net", "Machine Learning", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("hawkinsvictoria@example.net", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("joanngolden@example.net", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("joanngolden@example.net", "Reseau", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("joanngolden@example.net", "Statistiques", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("joanngolden@example.net", "Communication", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("joanngolden@example.net", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("joanngolden@example.net", "Analyse Numérique", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("vbeltran@example.org", "Cloud Computing", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("vbeltran@example.org", "Reseau", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("vbeltran@example.org", "Statistiques", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("vbeltran@example.org", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("vbeltran@example.org", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("vbeltran@example.org", "Analyse Numérique", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("tatejacqueline@example.com", "Cloud Computing", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("tatejacqueline@example.com", "Reseau", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("tatejacqueline@example.com", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("tatejacqueline@example.com", "Communication", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("tatejacqueline@example.com", "Machine Learning", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("tatejacqueline@example.com", "Analyse Numérique", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jennifercastillo@example.net", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jennifercastillo@example.net", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jennifercastillo@example.net", "Statistiques", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jennifercastillo@example.net", "Communication", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jennifercastillo@example.net", "Machine Learning", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jennifercastillo@example.net", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("garzatammy@example.net", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("garzatammy@example.net", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("garzatammy@example.net", "Statistiques", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("garzatammy@example.net", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("garzatammy@example.net", "Machine Learning", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("garzatammy@example.net", "Analyse Numérique", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jblack@example.net", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jblack@example.net", "Reseau", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jblack@example.net", "Statistiques", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jblack@example.net", "Communication", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jblack@example.net", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("jblack@example.net", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("umora@example.com", "Cloud Computing", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("umora@example.com", "Reseau", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("umora@example.com", "Statistiques", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("umora@example.com", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("umora@example.com", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("umora@example.com", "Analyse Numérique", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidramirez@example.com", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidramirez@example.com", "Reseau", "11");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidramirez@example.com", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidramirez@example.com", "Communication", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidramirez@example.com", "Machine Learning", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("davidramirez@example.com", "Analyse Numérique", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("staceyjohnson@example.org", "Cloud Computing", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("staceyjohnson@example.org", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("staceyjohnson@example.org", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("staceyjohnson@example.org", "Communication", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("staceyjohnson@example.org", "Machine Learning", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("staceyjohnson@example.org", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("leonard63@example.org", "Cloud Computing", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("leonard63@example.org", "Reseau", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("leonard63@example.org", "Statistiques", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("leonard63@example.org", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("leonard63@example.org", "Machine Learning", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("leonard63@example.org", "Analyse Numérique", "14");
INSERT INTO `notes` (username ,matiere, note) VALUES ("roycarney@example.org", "Cloud Computing", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("roycarney@example.org", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("roycarney@example.org", "Statistiques", "17");
INSERT INTO `notes` (username ,matiere, note) VALUES ("roycarney@example.org", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("roycarney@example.org", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("roycarney@example.org", "Analyse Numérique", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bailey05@example.com", "Cloud Computing", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bailey05@example.com", "Reseau", "13");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bailey05@example.com", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bailey05@example.com", "Communication", "16");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bailey05@example.com", "Machine Learning", "12");
INSERT INTO `notes` (username ,matiere, note) VALUES ("bailey05@example.com", "Analyse Numérique", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mjames@example.org", "Cloud Computing", "18");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mjames@example.org", "Reseau", "15");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mjames@example.org", "Statistiques", "20");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mjames@example.org", "Communication", "19");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mjames@example.org", "Machine Learning", "10");
INSERT INTO `notes` (username ,matiere, note) VALUES ("mjames@example.org", "Analyse Numérique", "19");

/* PROFS*/

INSERT INTO `accountsProf` (username ,password, nom, prenom, typeAcc, matiere) VALUES ("stephenlynn@example.org", "Kl+6LXlwCA", "Richmond", "Jason", "prf", "Cloud Computing");
INSERT INTO `accountsProf` (username ,password, nom, prenom, typeAcc, matiere) VALUES ("rebekahryan@example.com", "349*30Vq&i", "Henderson", "Bryan", "prf", "Reseau");
INSERT INTO `accountsProf` (username ,password, nom, prenom, typeAcc, matiere) VALUES ("ericahoward@example.net", "m9FfShr1+K", "Norris", "Chelsea", "prf", "Statistiques");
INSERT INTO `accountsProf` (username ,password, nom, prenom, typeAcc, matiere) VALUES ("svilla@example.net", ")1Tq(&4n$x", "Carter", "Julie", "prf", "Communication");
INSERT INTO `accountsProf` (username ,password, nom, prenom, typeAcc, matiere) VALUES ("wigginsjessica@example.org", ")mt*5AwF%&", "Jackson", "Kevin", "prf", "Machine Learning");
INSERT INTO `accountsProf` (username ,password, nom, prenom, typeAcc, matiere) VALUES ("beverly10@example.com", "0D9KjD0JG(", "Moyer", "Lisa", "prf", "Analyse Numérique");

/* Etudiants */

INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("achang@example.org", "tnPEm4__%8", "Garcia", "Charles", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("ashleypham@example.org", "Lyk1#PKi!%", "Johnson", "Anthony", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("davismichael@example.org", "4#czItpP+v", "Marshall", "Lucas", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("brittanyanderson@example.net", "9nC5zMtN*+", "Powers", "Caleb", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("kevingriffith@example.com", "#t1CaR80*3", "Collins", "Courtney", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("judy80@example.com", "F$0*6gIdqF", "Martinez", "Aaron", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("washingtonjose@example.org", "gP@O9qyR&#", "Rogers", "Christopher", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("stacie60@example.org", "(P#L^&sn)1", "Williams", "Michele", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("mitchellbennett@example.org", "+z3CeLO20&", "Russell", "Rachel", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("raustin@example.org", "#0Kqdf0wwJ", "Anderson", "Monica", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("pattersonbelinda@example.org", "l#*^7hIu_E", "Jennings", "Dorothy", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("xglenn@example.com", "1P8k&ASgd*", "Dean", "Marie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("hadams@example.net", "^NZMpa!Yy2", "Fuentes", "Charles", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("kelly23@example.net", "1#oh3)Uxzn", "Avery", "Laura", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("gilbertkarina@example.net", "9^4MXit7$B", "Martin", "Elizabeth", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("alexanderfitzgerald@example.org", "cpz0Bz87$p", "Fisher", "Barbara", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("taylor46@example.org", "*5N9vbwW@0", "Aguirre", "Elizabeth", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("xroman@example.com", "8@Vi6PBo#H", "Hernandez", "Janice", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("davidcole@example.org", "197UspQi0$", "Romero", "Lisa", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("gloverabigail@example.net", "967LC7*q$U", "Price", "Jessica", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("jordanreid@example.org", "I9*BwLFa^C", "Sullivan", "Jamie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("robertbarnes@example.com", "*PPZ!Fp^k3", "Ramos", "Summer", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("johnaustin@example.com", "#k^7XyuSg1", "Lee", "Melissa", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("patricia10@example.net", "%f76XMqyO@", "Logan", "Brianna", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("lfranco@example.org", "#eFl8u!v3Z", "Stevenson", "Sean", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("amack@example.org", "6A7V)Bny%Y", "Warren", "Nicole", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("donnareynolds@example.net", "!gYyJ5hf22", "Webb", "Kathy", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("smiles@example.org", "@Fm1t1IrU^", "Smith", "Terri", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("newtonamy@example.net", "MI3GEu1##*", "Salazar", "Samantha", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("reedmegan@example.com", "Iy@84DLmWJ", "Mueller", "Emily", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("cheryl93@example.com", ")6!QuMut!R", "Morales", "John", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("harrisonkathryn@example.org", "_E_y#%dgQ0", "Peterson", "Jamie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("houseduane@example.net", "7CCAdzMx$j", "Copeland", "Stephanie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("crystalmontoya@example.com", "8svBcN8f*Q", "Heath", "Erica", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("brenda30@example.com", "1VN*D!jQ^F", "Chapman", "Dana", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("karen52@example.com", "&4u8FSVbEw", "Simon", "Matthew", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("brian04@example.org", "6!8USUfyDl", "Palmer", "Jacqueline", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("mcconnellelizabeth@example.net", "_8kyLkByu_", "Roberts", "Michael", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("upatterson@example.org", "Fo0W7CfN@5", "Freeman", "Samuel", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("jordanjohnson@example.org", "l9ew#bAF&u", "Evans", "Jennifer", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("hriley@example.org", "$)VrK#suZ4", "Edwards", "John", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("kcook@example.com", ")gRjioK++4", "Wilson", "Briana", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("johnsonjoshua@example.org", "s&J1VP@xa#", "Pacheco", "Adam", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("mitchellkathryn@example.com", "O1OFpStK^o", "Davenport", "David", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("smeyer@example.org", "##!+6HdGHj", "Moore", "William", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("robert41@example.com", "!^(0h#C)kp", "Russell", "Jackie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("rossbrianna@example.org", "R_#jY8Es9C", "Moore", "Steven", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("bryan87@example.net", "H$I4*QmNS^", "Young", "Willie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("david84@example.net", "$6Fa4Poe4^", "Wolfe", "Kelly", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("coopersarah@example.com", "(8Zb$S4r9F", "Henderson", "Nicholas", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("xfoley@example.net", "&kc&+7YB1$", "Sexton", "Sydney", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("marytran@example.org", "$8dQIaG8m!", "Johnson", "Erica", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("brian87@example.com", "yln&0!Ef5+", "Martinez", "Arthur", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("stephendawson@example.net", "fp(5zX7o0E", "Romero", "Deborah", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("scottevans@example.com", "UG3rO%kS&S", "Davis", "Debbie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("travisjames@example.net", "1EfXfSGI%J", "Palmer", "Alexis", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("wellsalexandra@example.net", "X&3D@UlV_c", "Mendez", "Angelica", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("richardsoncatherine@example.org", "yKnFP0tj(5", "Li", "Christina", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("jamiemay@example.org", "E3qxlJOm!M", "Keller", "Bryan", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("christophersantos@example.com", "@2JNNwA+!z", "Davidson", "Meghan", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("justin24@example.org", "kpK1b5k!*7", "Carlson", "Lisa", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("nwhite@example.com", "%E5MZCwP&0", "Bullock", "Joanna", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("cameronbriggs@example.com", "1%5FqqM@qw", "Gardner", "Anna", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("qwallace@example.com", "_a9Mxh%av1", "Kaufman", "Roberta", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("nmartinez@example.com", "(0G2maipKf", "Garcia", "Brandon", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("groberts@example.org", "S7Qs^o7a*$", "Richardson", "Denise", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("collinssandra@example.com", "4Zo1Qter%I", "Cameron", "Tina", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("wilsonricky@example.com", "&8rTb9n1c4", "Sanders", "Alisha", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("veverett@example.net", "@9pCySShj$", "Davis", "Catherine", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("davisgarrett@example.net", "pI^5ZBzKIH", "Thomas", "Kyle", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("carterstephen@example.org", "^1bl5EPvFr", "Campbell", "Dennis", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("william04@example.org", "$VPCQug)Z4", "Sheppard", "Manuel", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("caseyjoanna@example.org", "^8y)Td5l#l", "Davis", "Lonnie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("david79@example.org", "*Q4(SjcEJS", "Carroll", "James", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("floreslauren@example.org", "lQ5D8Yo$w$", "Adams", "Wanda", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("drichards@example.org", "utco8Vdvi+", "Ortiz", "Nicholas", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("steven63@example.com", "AoO6oHj%a!", "Daniels", "Angel", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("mark33@example.org", "5%7!8Rtk2z", "Miller", "Kimberly", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("codyglass@example.net", "%a61dBun50", "Harris", "Craig", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("samuelcarlson@example.org", "$2yO7EncmG", "Ball", "Tonya", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("phillip65@example.com", "So6Lva5wT(", "Gomez", "Gilbert", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("imorgan@example.com", "LiFteEA)*0", "Vang", "Kimberly", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("kaylalucero@example.com", "+#2V*Voi&C", "Monroe", "John", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("danthony@example.org", "#36ByIEb2k", "Harrington", "Andrew", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("robin07@example.org", "OS5GSh7or(", "Williams", "Lisa", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("jacquelinewilkins@example.com", "$3VcRoOcyM", "Jones", "Taylor", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("hawkinsvictoria@example.net", "!A1WrqzI!i", "Foster", "Patricia", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("joanngolden@example.net", "Z@4Yk@G&OX", "Lyons", "Stephanie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("vbeltran@example.org", "d_0_Q)_yIb", "Bryan", "Matthew", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("tatejacqueline@example.com", "#e3dCC0X5V", "Jones", "Thomas", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("jennifercastillo@example.net", "l)xAO4UlyY", "Anderson", "Kayla", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("garzatammy@example.net", "g6n6OFOz#h", "Hughes", "Kristen", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("jblack@example.net", ")bZUMozUY4", "Webb", "Emily", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("umora@example.com", "0)1LS(Yet@", "Phillips", "Kelly", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("davidramirez@example.com", "!n7@!KLjlb", "Green", "Christopher", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("staceyjohnson@example.org", "l$1XYUikF)", "Burke", "Caitlin", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("leonard63@example.org", "0Z&0EWla^S", "Kerr", "Nicole", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("roycarney@example.org", "$rm0RKym)A", "Thompson", "Daniel", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("bailey05@example.com", "!Tkt7Jxi!j", "Williams", "Julie", "etd");
INSERT INTO `accountsEtd` (username ,password, nom, prenom, typeAcc) VALUES ("mjames@example.org", "&f$3&EyfVk", "Murray", "Harold", "etd");
