CREATE DATABASE IF NOT EXISTS gestn;
USE gestn;

CREATE TABLE IF NOT EXISTS accountsEtd (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    typeAcc VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS accountsProf (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    typeAcc VARCHAR(255) NOT NULL,
    matiere VARCHAR(255) NOT NULL
);
